- type: entity
  abstract: true
  id: ClothingTopless
  components:
  - type: HideLayerClothing
    slots:
    - Genital
    - Penis

- type: entity
  abstract: true
  id: ClothingBottomless
  components:
  - type: HideLayerClothing
    slots:
    - Breasts

- type: entity
  abstract: true
  id: ClothingNude
  components:
  - type: HideLayerClothing
    slots: []
